### ISSUE TITLE
Failed to load sandbox db engine

### ISSUE THREAD

**Issue by AtlasPerformance** [zephyrj/engine-crane#27] opened 2024-02-11 15:32 UTC
I've had numerous issues even being able to access the beamng 'mod' and I had to eventually just drop the mod onto my desktop, which seemed to work, but now it's telling me that theres no sandbox file for the 4.3 Ellisbury update, or something like that. I don't know if the issues I was having are contributing to this, or if this is a separate issue, but regardless I'm unable to make the swap work.
![Capture](https://github.com/zephyrj/engine-crane/assets/74026580/f86f7986-dc06-4de9-8000-b0b325d1e8bf)

**Comment by zephyrj** [comment] 2024-02-12 19:49
Hi, do you have your engine_crane.log file available for me to look at? It will be present in the same directory that you run engine-crane from

If you're having issue with it picking up the BeamNG mod path it could be related to this as the default location will be inside `C:\Users\<your username>\AppData\Local` which is the same location where the Automation sandbox.db files will be located

**Comment by AtlasPerformance** [comment] 2024-02-12 22:35
How do I access the engine_crane.log file? (I am very new to modding, so apologies for the lack of understanding.)

And yes, the default location is indeed in AppData\Local, I tried for like an hour to try to figure out how to access that path through the 'Browse' feature of engine crane, but as long as it won't cause any issues with accessing the mod from my desktop, that system works just fine.

**Comment by zephyrj** [comment] 2024-02-13 19:01
No need to apologize. The engine_crane.log file will get written into the same folder that the engine-crane.exe is in when you run it.

The issue if the AppData\Local path is inacessibke is that that is where Automation saves the sandbox.db it is looking for - so in order for it to work at all then engine-crane will need access to it

**Comment by AtlasPerformance** [comment] 2024-02-13 23:04
Aha, I found it, I'm unsure of what you are looking for in here, but heres a sample of the log -
2024-02-13T23:02:20.066324Z  INFO Creating new car spec: assetto_corsa::car: Cloning C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988 to C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap
2024-02-13T23:02:21.127753Z  INFO Creating new car spec: assetto_corsa::car: No data dir present in C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap. Data will be extracted from data.acd
2024-02-13T23:02:21.160679Z  INFO Creating new car spec: assetto_corsa::car: Updating LOD_0
2024-02-13T23:02:21.162670Z  INFO Creating new car spec: assetto_corsa::car: Changing C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap\porsche_944_turbo_s_1988.kn5 to porsche_944_turbo_s_1988_stock_4200_swap.kn5
2024-02-13T23:02:21.267245Z  INFO Creating new car spec: assetto_corsa::car: Changing C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap\sfx\porsche_944_turbo_s_1988.bank to porsche_944_turbo_s_1988_stock_4200_swap.bank
2024-02-13T23:02:21.267625Z  INFO Creating new car spec: assetto_corsa::car: Updating contents of 'C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap\sfx\GUIDs.txt'. Replacing refs to 'porsche_944_turbo_s_1988' with 'porsche_944_turbo_s_1988_stock_4200_swap'
2024-02-13T23:02:21.273724Z  INFO Creating new car spec: assetto_corsa::car: Packing C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap\data into an .acd file
2024-02-13T23:02:21.547185Z  INFO Creating new car spec: assetto_corsa::car: Deleting C:\Program Files (x86)\Steam\steamapps\common\assettocorsa\content\cars\porsche_944_turbo_s_1988_stock_4200_swap\data as data will be invalid after clone completion
2024-02-13T23:02:21.557885Z  INFO Creating new car spec: assetto_corsa::car: Updating screen name and ui data from Porsche 944 Turbo S (1988) to Porsche 944 Turbo S (1988) stock_4200_swap
2024-02-13T23:02:21.671655Z  INFO Creating new car spec: assetto_corsa::car: Updating parent name
2024-02-13T23:02:21.671681Z  INFO Creating new car spec: assetto_corsa::car: Added engine crane tag
2024-02-13T23:02:21.672159Z  INFO Updating car physics from BeamNG mod: engine_crane::fabricator: Creating AC parameter calculator for BeamNG mod C:\Users\cj\Desktop\stock_4200_swap.zip
2024-02-13T23:02:21.672172Z  INFO Updating car physics from BeamNG mod: beam_ng: Opening C:\Users\cj\Desktop\stock_4200_swap.zip
2024-02-13T23:02:21.678666Z  INFO Updating car physics from BeamNG mod: beam_ng: Extracting C:\Users\cj\Desktop\stock_4200_swap.zip
2024-02-13T23:02:21.684626Z  INFO Updating car physics from BeamNG mod: engine_crane::fabricator: Loading Automation car file
2024-02-13T23:02:21.684748Z  INFO Updating car physics from BeamNG mod: engine_crane::fabricator: Engine version number: 2401240000
2024-02-13T23:02:21.684755Z  INFO Updating car physics from BeamNG mod: engine_crane::fabricator: Deduced as 4.3 Ellisbury
2024-02-13T23:02:21.684760Z  INFO Updating car physics from BeamNG mod: engine_crane::fabricator: Engine uuid: A028264C4D4DCEC7F7E59B89D2632AC3
2024-02-13T23:02:21.684766Z  INFO Updating car physics from BeamNG mod: beam_ng: Expect to find engine data in camso_engine_A0282.jbeam
2024-02-13T23:02:21.684776Z  INFO Updating car physics from BeamNG mod: beam_ng: Found engine.jbeam file at vehicles/stock_4200/eng_a0282/camso_engine_a0282.jbeam
2024-02-13T23:02:21.756078Z ERROR engine_crane::ui: failed to load `Sandbox db engine A028264C4D4DCEC7F7E59B89D2632AC3`. `No sandbox db file available for 4.3 Ellisbury`

Ah, yeah that makes sense, but what I find weird is that engine crane was able to locate my Assetto Corsa files without issue, it's just BeamNG Drive that it had issues accessing, but I see where that could lead to issues. If thats the suspected issue, how do I go about fixing this?

**Comment by zephyrj** [comment] 2024-02-14 19:02
Would you be able to attach the whole log file for me to look through please? It should print out where it's looking for/finding the Automation sandbox db files for various versions. You can use the "Attach Files" option when adding a comment - it's a paperclip icon

The Assetto Corsa files all live in `Program Files (x86)` unless you have a custom steam library location - in which case they will be in there. Generally that won't be in AppData

I'm not that familiar with Windows file management (I use Linux day-to-day) so I'm unaware of the various permissions that Windows sets up. Do you have multiple drives configured on your computer? Or perhaps use different user accounts?

**Comment by AtlasPerformance** [comment] 2024-02-15 05:18
[engine_crane.log](https://github.com/zephyrj/engine-crane/files/14291732/engine_crane.log)

My father configured this PC, so I honestly don't know exactly how its configured, but I do know that there are different user accounts. When I was trying to browse for the BeamNG mod path, I would re-trace the steps it took for me to get there  through the browse menu, but I would get this error every time ![image](https://github.com/zephyrj/engine-crane/assets/74026580/092f7f31-f3fc-41ba-9f3b-f23fefe4ca7a) (in order to access it, I would have to click on this type of folder that appeared to be some sort of shortcut, and one of them, I think, was going to an older version of BeamNG and thats what caused the error?
When I go through that same path through the standard files program, there are no issues or errors when accessing the BeamNG mod path.

**Comment by zephyrj** [comment] 2024-02-15 18:25
I've had a little look through the logs and I have a theory is that the issue is to do with different users that are set up. 

Based on what I can see in the logs it seems that engine-crane is being run by the `CJAdmin` user which makes sense as it asks for admin rights to launch (this is so it can find Assetto Corsa in `ProgramFiles (x86)`). It also appears that there is a regular `cj` user that is separate.

As `CJAdmin` is almost certainly the admin account. I suspect you can't access this users data when running as the `cj` user as that account is not running as admin. I think that explains the error you are seeing with the "moved here" folder from your screenshot. 

I also suspect there may be both of the following locations
```
C:\Users\CJAdmin\AppData\Local\
C:\Users\cj\AppData\Local\
```

engine-crane can't find any Automation data in `CJAdmin` but I wonder Automation gets run under the regular `cj` user - this makes me wonder if your sandbox data is stored in
```
C:\Users\cj\AppData\Local\AutomationGame\Saved\UserData
```

Would you be able to check whether you can access this and verify what files are in it if it does exist?

**Comment by AtlasPerformance** [comment] 2024-02-15 21:48
All of that does make a lot of sense regarding the issues I've been experiencing. After looking, I was able to locate my Automation folder in this pathway - 
![image](https://github.com/zephyrj/engine-crane/assets/74026580/4a9f5993-3a52-4191-81b4-b29ee674e4d9)

Also, I can access the CJAdmin files from the cj account with the password, which is another kinda odd thing I need to do in order to open the engine crane program.

**Comment by zephyrj** [comment] 2024-02-18 21:00
I've just made a set of changes which should allow you to manually set the path to your Automation sandbox.db files. You can download this version from the releases page: https://github.com/zephyrj/engine-crane/releases/tag/v0.3.2-alpha. In this version you can now change where engine-crane looks for the Automation saved data in the Settings tab.

The ProgramFiles location doesn't hold your saved Automation userdata (sandbox.db files) so you'll still need to find where they are being stored on your computer and update the path in the Settings tab engine-crane. For your purposes you can ignore the Legacy Automation path and instead only set the other one

As I mentioned in my previous message it is highly likely they are stored somewhere like
```
C:\Users\cj\AppData\Local\AutomationGame\Saved\UserData
```
though the username (cj) may be differ.

To help you find them - you're looking for the folder which contains the following filenames:
```
Sandbox_230915.db
Sandbox_211122.db
```

Hope this helps you get it working

**Comment by AtlasPerformance** [comment] 2024-02-19 05:42
Thank you for releasing a whole fix for your program based on my issue, however, I am unfortunately getting the same error. For the Automation data path location, I just have it set to the game, do I perhaps need to select a folder within the game files?
![image](https://github.com/zephyrj/engine-crane/assets/74026580/34c5f90a-361b-4496-906b-f0934ac7f290)

Here is also the data paths I have set up. I'm unsure as to what the Legacy Automation Data Path is, so maybe I just need to set that up?
![image](https://github.com/zephyrj/engine-crane/assets/74026580/36dcf21a-9f02-44c0-a8ad-239557c9bc98)

**Comment by zephyrj** [comment] 2024-02-19 18:59
Perhaps manually setting the config will work for you

You should be able to take that address from the first screen, click a blank part in the search bar after `UserData` and it should show the full path as text. Copy that.

In the folder where engine-crane.exe lives you should see a `engine-crane-conf.toml`. Open that in notepad and edit the file so that you replace the `automation_userdata_path` part (leaving the rest as it is) as follows:
```toml
automation_userdata_path = "The path you just copied"
```

**Comment by AtlasPerformance** [comment] 2024-02-20 01:15
YES! That worked! Thank you so much for helping me troubleshoot this and for all of your support!

**Comment by zephyrj** [comment] 2024-02-20 07:26
Excellent, glad to hear. I'll close this issue now it has been resolved. Have fun with engine-crane :)

**Closed** 2024-02-20 07:26 UTC
